# Copyright (c) 2026 Qira LLC. All rights reserved.
"""Runtime Self-Description Manifest.

Generated by the harness, not the model. Self-description answers may only
assert capabilities present in the manifest.
"""

from __future__ import annotations

import hashlib
import json
import platform
import time
from dataclasses import asdict, dataclass, field
from typing import Any, Dict, List, Optional, Set


@dataclass
class RuntimeManifest:
    schema: str = "lolm.runtime_manifest.v1"
    cli_version: str = ""
    server_commit: str = ""
    controller_version: str = "reliability-v1-2026-08"
    reasoner_profile: str = ""
    active_model: str = ""
    graft_state: str = "unknown"  # loaded | offline | synthetic
    network_enabled: bool = False
    tools: List[str] = field(default_factory=list)
    memory_enabled: bool = False
    browser_verifier: str = ""  # chromium | static_lint | none
    filesystem_scope: str = "sandbox"
    data_sources: List[str] = field(default_factory=list)
    capabilities: List[str] = field(default_factory=list)
    generated_at: float = 0.0
    manifest_sha256: str = ""

    def to_dict(self) -> Dict[str, Any]:
        d = asdict(self)
        return d

    def sign(self) -> str:
        core = {k: v for k, v in self.to_dict().items() if k != "manifest_sha256"}
        raw = json.dumps(core, sort_keys=True, separators=(",", ":"), default=str)
        self.manifest_sha256 = hashlib.sha256(raw.encode()).hexdigest()
        return self.manifest_sha256

    def allows_claim(self, claim: str) -> bool:
        """Return whether a natural-language capability claim is grounded."""
        c = (claim or "").lower()
        caps = {x.lower() for x in self.capabilities}
        tools = {x.lower() for x in self.tools}
        # Broad unsupported claims
        if "one transformer model" in c and self.reasoner_profile:
            # We are a controller + reasoner stack, not a single transformer claim
            if "controller" not in c and "nfet" not in c:
                return False
        if "external knowledge" in c or "browse the whole internet" in c:
            if not self.network_enabled and "network.outbound" not in caps:
                return False
        if "xdg-open" in c or "open a desktop browser" in c:
            if "desktop.open" not in caps:
                return False
        return True

    def self_description_text(self) -> str:
        """Grounded identity answer — inject into capability questions."""
        parts = [
            "I am LOLM: a controller-mediated coding and conversation system, "
            "not a single opaque transformer.",
            f"Controller version: {self.controller_version}.",
        ]
        if self.cli_version:
            parts.append(f"CLI: {self.cli_version}.")
        if self.reasoner_profile:
            parts.append(f"Reasoner profile: {self.reasoner_profile}.")
        if self.active_model:
            parts.append(f"Active model (if disclosed): {self.active_model}.")
        parts.append(f"Graft/NFET state: {self.graft_state}.")
        parts.append(f"Filesystem scope: {self.filesystem_scope}.")
        parts.append(f"Browser verifier: {self.browser_verifier or 'none'}.")
        parts.append(f"Network: {'enabled' if self.network_enabled else 'disabled in this environment'}.")
        if self.tools:
            parts.append("Tools: " + ", ".join(self.tools[:20]) + ".")
        if self.capabilities:
            parts.append("Capabilities: " + ", ".join(self.capabilities[:20]) + ".")
        if self.data_sources:
            parts.append("Data sources actually used this session: "
                         + ", ".join(self.data_sources[:10]) + ".")
        else:
            parts.append("No external data sources used yet this session.")
        parts.append(
            "I distinguish controller policy, backbone reasoner, CLI shell, and verifiers. "
            "Claims outside this manifest are not asserted."
        )
        return " ".join(parts)


def build_runtime_manifest(
    *,
    cli_version: str = "",
    server_commit: str = "",
    reasoner_profile: str = "",
    active_model: str = "",
    graft_state: str = "synthetic",
    network_enabled: bool = False,
    tools: Optional[List[str]] = None,
    memory_enabled: bool = False,
    browser_verifier: str = "static_lint",
    filesystem_scope: str = "sandbox",
    data_sources: Optional[List[str]] = None,
    capabilities: Optional[List[str]] = None,
) -> RuntimeManifest:
    m = RuntimeManifest(
        cli_version=cli_version,
        server_commit=server_commit,
        reasoner_profile=reasoner_profile or f"host={platform.platform()}",
        active_model=active_model,
        graft_state=graft_state,
        network_enabled=network_enabled,
        tools=list(tools or ["sandbox.run", "sandbox.write", "syntax.python", "html.static_lint"]),
        memory_enabled=memory_enabled,
        browser_verifier=browser_verifier,
        filesystem_scope=filesystem_scope,
        data_sources=list(data_sources or []),
        capabilities=list(capabilities or [
            "python3", "syntax.python", "html.static_lint", "html.render", "pdf.exists", "unittest",
        ]),
        generated_at=time.time(),
    )
    m.sign()
    return m
